core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre/', views.sobre, name='sobre'),
    path('search_result/', views.search_result, name='search_results'),
    path('available_locations/', views.available_locations, name='available_locations'),
    path('info_ambientes/local/<int:local_id>/', views.info_ambientes, name='info_ambientes'),
]

mapa/urls.py
from django.urls import path
from . import views

app_name = 'mapa'

urlpatterns = [
    path('locais/', views.listar_locais, name='listar_locais'),
    path('predios/', views.listar_predios, name='listar_predios'),
    path('mapas/', views.mapas, name='mapa'),
    path('favoritar_local/<int:local_id>/', views.favoritar_local, name='favoritar_local'),
    path('favoritar_predio/<int:predio_id>/', views.favoritar_predio, name='favoritar_predio'),
    path('favoritar-login-required/', views.login_required_message, name='favoritar_login_required'),
]

pucgo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("core.urls")),
    path('accounts/', include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("mapa.urls")),
    path("rotas/", include("rota.urls")),
]

mapa/models.py
from django.db import models
from django.contrib.auth.models import User


class Predio(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True)
    coordenadas = models.JSONField(null=True, blank=True)  
    
    class Meta:
        verbose_name_plural = "Prédios"
    
    def __str__(self):
        return self.nome

class Local(models.Model):
    TIPO_CHOICES = [
        ('sala de aula', 'Sala de aula'),
        ('banheiro', 'Banheiro'),
        ('restaurante', 'Restaurante'),
        ('biblioteca', 'Biblioteca'),
        ('administrativo', 'Administrativo'),
        ('laboratório', 'Laboratório'),
        ('outro', 'Outro'),
    ]
    
    nome = models.CharField(max_length=100)
    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
    descricao = models.TextField()
    predio = models.ForeignKey(Predio, on_delete=models.CASCADE, related_name='locais')
    andar = models.CharField(max_length=50)
    localizacao_detalhada = models.TextField(null=True, blank=True)
    coordenadas = models.JSONField(null=True, blank=True)
    informacoes_extras = models.JSONField(null=True, blank=True)
    ativo = models.BooleanField(default=True)

    search_count = models.PositiveIntegerField(default=0)
    sugerido_padrao = models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural = "Locais"
        ordering = ['predio', 'andar', 'nome']
    
    def __str__(self):
        return f"{self.nome} - {self.predio.nome}"
    


class FavoritoPredio(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favoritos_predios'
    )
    predio = models.ForeignKey(
        Predio,
        on_delete=models.CASCADE,
        related_name='favoritado_por'
    )
    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'predio')
        verbose_name = "Prédio Favorito"
        verbose_name_plural = "Prédios Favoritos"

    def __str__(self):
        return f"{self.user.username} favoritou o prédio {self.predio.nome}"


class FavoritoLocal(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favoritos_locais'
    )
    local = models.ForeignKey(
        Local,
        on_delete=models.CASCADE,
        related_name='favoritado_por'
    )
    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'local')
        verbose_name = "Local Favorito"
        verbose_name_plural = "Locais Favoritos"

    def __str__(self):
        return f"{self.user.username} favoritou o local {self.local.nome}"

mapa/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse


from .models import Local, Predio, FavoritoLocal, FavoritoPredio

def mapas(request):
    return render(request, 'mapa.html')


def listar_locais(request):
    tipo = request.GET.get('tipo', None)
    
    locais = Local.objects.filter(ativo=True).select_related('predio')
    
    if tipo and tipo != 'todos':
        locais = locais.filter(tipo=tipo)
    
    dados = []
    for local in locais:
        dados.append({
            'id': local.id,
            'nome': local.nome,
            'tipo': local.tipo,
            'descricao': local.descricao,
            'predio': local.predio.nome,
            'andar': local.andar,
            'localizacao': local.localizacao_detalhada,
            'coordenadas': local.coordenadas,
            'extras': local.informacoes_extras
        })
    
    return JsonResponse(dados, safe=False)

def listar_predios(request):
    predios = Predio.objects.all()
    
    dados = []
    for predio in predios:
        dados.append({
            'id': predio.id,
            'nome': predio.nome,
            'descricao': predio.descricao,
            'coordenadas': predio.coordenadas,
            'total_locais': predio.locais.filter(ativo=True).count()
        })
    
    return JsonResponse(dados, safe=False)




@login_required(login_url='login')
def favoritar_local(request, local_id):
    local = get_object_or_404(Local, id=local_id)

    favorito, created = FavoritoLocal.objects.get_or_create(
        user=request.user,
        local=local
    )

    if not created:
        favorito.delete()  # se já existia, remove 

    return redirect(request.META.get('HTTP_REFERER', 'home')) # volta pra página anterior


@login_required(login_url='login')
def favoritar_predio(request, predio_id):
    predio = get_object_or_404(Predio, id=predio_id)

    favorito, created = FavoritoPredio.objects.get_or_create(
        user=request.user,
        predio=predio
    )

    if not created:
        favorito.delete()  

    return redirect(request.META.get('HTTP_REFERER', 'home'))


def login_required_message(request):
    messages.error(request, "Você precisa estar logado para favoritar locais.")
    referer = request.META.get('HTTP_REFERER')
    if referer:
        return redirect(referer)
    login_url = reverse('login')   # espera que exista name='login'
    next_path = request.get_full_path() or '/'
    return redirect(f"{login_url}?next={next_path}")

templates/info_ambientes.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'CSS/style_info_ambientes.css' %}">
{% endblock %}

{% block title %}PUC-Go — Informações do local{% endblock %}

{% block content %}

    <div class = "resultados">
        <p class = "titulo-res">Mais informações</p>
    </div>
        
        {% if local %}
            <div class="container-pesq">
                <div class="img-res">
                    <i data-lucide="building" class="icone-predio2"></i>
                    <p class="titulo-card">{{ local.predio.nome }}</p>
                    <p class="subtit-card"> 
                            {% if local.andar.isdigit %}
                                {{ local.andar }}º andar
                            {% else %}
                                {{ local.andar }}
                            {% endif %}
                    </p>
                </div>
                <div class="res-txt">
                    <div class="div-pesq">
                        <p class="nome-pesq">{{ local.nome }}</p>
                        
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'mapa:favoritar_local' local.id %}">
                            {% csrf_token %}
                                <button type="submit" class="favorites-btn2" aria-label="Favoritar local">
                                    {% if local.id in favoritos_locais_ids %}
                                        <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                                    {% else %}
                                        <i data-lucide="heart" class="icone-coracao-vazio"></i>
                                    {% endif %}
                                </button>
                            </form>
                        {% else %}
                                <a href="{% url 'mapa:favoritar_login_required' %}" class="favorites-btn2">
                                    <i data-lucide="heart" class="icone-coracao-vazio"></i>
                                </a>
                        {% endif %}
                    
                    </div>

                    <div class="div-pesq2">
                        <i data-lucide="building" class="icone-textos"></i>
                        <p class="text-pesq">{{ local.predio.nome }}</p>
                    </div>
                    <div class="div-pesq2">
                        <i data-lucide="layers" class="icone-textos"></i>
                        <p class="text-pesq">{% if local.andar.isdigit %}
                                                {{ local.andar }}º andar
                                            {% else %}
                                                {{ local.andar }}
                                            {% endif %} </p>
                    </div>
                    <div class="div-pesq2">
                        <i data-lucide="door-open" class="icone-textos"></i>
                        <p class="text-pesq">{{ local.get_tipo_display }}</p>
                    </div>
                    <div class="div-pesq3">
                        <div class="div-pesq">
                            <p class="tit-inf-adc">Informações Adicionais</p>
                        </div>
                        <div class="div-pesq4">
                            {% if local.descricao %}
                            <p class="text-pesq">
                                {{ local.descricao }}
                            </p>
                             {% else %}
                            <p class="text-pesq">
                                Sem descrição disponível.
                            </p>
                            {% endif %}
                            
                        </div>
                    </div>    
                    {% load l10n %}
                    <div class="div-pesq5">
                        <a href="{% url 'mapa:mapa' %}?lat={{ local.predio.coordenadas.0|unlocalize }}&lng={{ local.predio.coordenadas.1|unlocalize }}" class="marcar-btn">
                            <span data-lucide="map-pinned" class="icones-btns"></span>Marcar como destino
                        </a>
                    </div>
                </div>
    </div>

    {% else %}
        <div class="resultados">
            <p class="quant-res">Nenhum local encontrado.</p>
        </div>
    {% endif %}


{% endblock %}

templates/locais_disponiveis.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'CSS/style_locais_disponiveis.css' %}">
{% endblock %}

{% block title %}PUC-Go — Locais Disponíveis{% endblock %}

{% block content %}



    <main class = "container-predio">

    <div class = "title">
        <h1 class = "predio">Locais Disponíveis</h1>
        <p class = "descricao">Encontre salas, banheiros e restaurantes no campus</p>
    </div>

    <section class = "place_cards">
    <nav class="tabs">
                {# Aba "Todos" #}
            <form method="get">
                <input type="hidden" name="tipo" value="todos">
                <button type="submit"
                        class="{% if selected_tipo == 'todos' %}active{% endif %}">
                    Todos
                </button>
            </form>

                {# Aba "Prédios" #}
            <form method="get">
                <input type="hidden" name="tipo" value="predio">
                <button type="submit"
                        class="{% if selected_tipo == 'predio' %}active{% endif %}">
                    Prédios
                </button>
            </form>

            {# Abas por tipo - pegando do TIPO_CHOICES #}
            {% for value, label in tipos %}
                <form method="get">
                    <input type="hidden" name="tipo" value="{{ value }}">
                    <button type="submit"
                            class="{% if selected_tipo == value %}active{% endif %}">
                        {{ label }}
                    </button>
                </form>
            {% endfor %}
    </nav>

    <div class = "all_locations">

        {% if selected_tipo == 'todos' or selected_tipo == 'predio' %}
            {% for predio in predios %}
                <div class="card-localizacao">
                    <p class="titulo">{{ predio.nome }}</p>
                    <p class="subtitulo">Prédio</p>

                    {% if user.is_authenticated %}
                        <a href="{% url 'mapa:favoritar_predio' predio.id %}">
                            {% if predio.id in favoritos_predios_ids %}
                                <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                            {% else %}
                                <i data-lucide="heart" class="icone-coracao-vazio"></i>
                            {% endif %}
                        </a>
                    {% else %}
                            <a href="{% url 'mapa:favoritar_login_required' %}" class="favorites-btn2">
                                <i data-lucide="heart" class="icone-coracao-vazio"></i>
                            </a>
                    {% endif %}

                    <p class="descr">
                        {{ predio.descricao|default:"Sem descrição disponível." }}
                    </p>

                    <i data-lucide="map-pin" class="icone-pin"></i>
                    <p class="local">
                        {{ predio.nome }} 
                    </p>
                    {% load l10n %}
                    <div class="botoes-card-predio">
                        <a href="{% url 'mapa:mapa' %}?lat={{ predio.coordenadas.0|unlocalize }}&lng={{ predio.coordenadas.1|unlocalize }}" class="btn-marcar-destino-predio">
                            <span class="texto-marcar-destino"></span>Marcar como destino
                        </a>
                    </div>

                </div>
            {% endfor %}
        {% endif %}
        
        {% if selected_tipo != 'predio' %}
            {% for local in locais %}
                        <div class="card-localizacao">
                            <p class="titulo">{{ local.nome }}</p>
                            <p class="subtitulo">{{ local.predio.nome }}</p>

                            {% if user.is_authenticated %}
                                <a href="{% url 'mapa:favoritar_local' local.id %}">
                                    {% if local.id in favoritos_locais_ids %}
                                        <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                                    {% else %}
                                        <i data-lucide="heart" class="icone-coracao-vazio"></i>
                                    {% endif %}
                                </a>
                            {% else %}
                                <a href="{% url 'mapa:favoritar_login_required' %}" class="favorites-btn2">
                                    <i data-lucide="heart" class="icone-coracao-vazio"></i>
                                </a>
                            {% endif %}

                            <p class="descr">
                            {{ local.descricao|default:"Sem descrição disponível." }}
                            </p>

                            <i data-lucide="map-pin" class="icone-pin"></i>
                            <p class="local">
                                {{ local.predio.nome }} – 
                                    {% if local.andar.isdigit %}
                                        {{ local.andar }}º andar
                                    {% else %}
                                        {{ local.andar }}
                                    {% endif %}
                            </p>
                            {% load l10n %}
                            <div class="botoes-card-loc">
                                <a href="{% url 'mapa:mapa' %}?lat={{ local.predio.coordenadas.0|unlocalize }}&lng={{ local.predio.coordenadas.1|unlocalize }}" class="btn-marcar-destino">
                                    <span class="texto-marcar-destino"></span>Marcar como destino
                                </a>
                                <a href="{% url 'info_ambientes' local.id %}" class="btn-mais-infos">
                                    <span data-lucide="info" class="icone-mais"></span>Mais informações
                                </a>
                            </div>
                        </div>
                    {% endfor %}
        {% endif %}
    </div>
  </main>



{% endblock %}

templates/localizacoes_favoritas.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'CSS/style_localizacoes_favoritas.css' %}">
{% endblock %}

{% block title %}PUC-Go — Localizações Favoritas{% endblock %}

{% block content %}




    <main class="conteudo-principal">
        <div class="container-secao-loc-favoritas">
            <h2>Localizações Favoritas</h2>
            <h3>Seus locais salvos no campus</h3>
        </div>


        <div class="container-cards-locais-favoritos">
             {# -------- PRÉDIOS FAVORITOS ---------- #}
            {% for fav in favoritos_predios %}
                {% load l10n %}
                <div class="card-localfav">
                    <p class="titulo">{{ fav.predio.nome }}</p>
                    <p class="subtitulo">{{ fav.predio.nome }}</p>

                
                    <a href="{% url 'mapa:favoritar_predio' fav.predio.id %}">
                    <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                    </a>

                    <p class="descr">
                        {{ fav.predio.descricao|default:"Sem descrição disponível." }}
                    </p>

                    <i data-lucide="map-pin" class="icone-pin"></i>
                    <p class="local">
                        {{ fav.predio.nome }}
                    </p>
                    <div class="botoes-card-predio">
                        <a href="{% url 'mapa:mapa' %}?lat={{ fav.predio.coordenadas.0|unlocalize }}&lng={{ fav.predio.coordenadas.1|unlocalize }}" class="btn-marcar-destino-predio">
                            <span class="texto-marcar-destino"></span>Marcar como destino
                        </a>
                    </div>


                </div>
    
            {% empty %}
            {# se não tiver prédios favoritos, não mostra nada aqui #}
            {% endfor %}

            {# -------- LOCAIS FAVORITOS --------- #}
            {% for fav in favoritos_locais %}
                <div class="card-localfav">
                    <p class="titulo">{{ fav.local.nome }}</p>
                    <p class="subtitulo">{{ fav.local.predio.nome }}</p>

                    <a href="{% url 'mapa:favoritar_local' fav.local.id %}">
                    <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                    </a>

                    <p class="descr">
                    {{ fav.local.descricao|default:"Sem descrição disponível." }}
                    </p>

                    <i data-lucide="map-pin" class="icone-pin"></i>
                    <p class="local">
                        {{ fav.local.predio.nome }} – 
                            {% if fav.local.andar.isdigit %}
                                {{ fav.local.andar }}º andar
                            {% else %}
                                {{ fav.local.andar }}
                            {% endif %}
                    </p>
                {% load l10n %}
                <div class="botoes-card-fav">
                <a href="{% url 'mapa:mapa' %}?lat={{ fav.local.predio.coordenadas.0|unlocalize }}&lng={{ fav.local.predio.coordenadas.1|unlocalize }}" class="btn-marcar-destino">
                    <span class="texto-marcar-destino"></span>Marcar como destino
                </a>
                    <a href="{% url 'info_ambientes' fav.local.id %}" class="btn-mais-infos">
                        <span data-lucide="info" class="icone-mais"></span>Mais informações
                    </a>
                </div>
                </div>
        {% empty %}
        
        {% endfor %}

        {% if not favoritos_predios and not favoritos_locais %}
            <p>Você ainda não tem localizações favoritas.</p>
        {% endif %}
        </div>
    </main>



{% endblock %}

templates/modalSuporte.html
<link rel="stylesheet" href="{% static 'CSS/style_base.css' %}">

<div id="modalInstrucoes" class="modal-overlay">
    <div class="modalAjuda">
        <div class="modal-cabecalho">
             <h2 class="modal-titulo">Suporte</h2>
        </div>
        
        <div class="modal-corpo-instrucoes">
            <ul>
                <li>Suporte:</li>
                <li>Se você deseja falar com a nossa equipe utilize os contatos disponíveis abaixo:</li>
                <li>Email: mapapucgo@gmail.com</li>
                <li>Tel.:00 00000-0000</li>
                <li>Se o caso for alguma dúvida sobre o site, tente buscar na página de -Ajuda-!</li>
            </ul>
        </div>

templates/resultado_pesquisa.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'CSS/style_resultado_pesquisa.css' %}">
{% endblock %}

{% block title %}PUC-Go — Resultado de Pesquisa{% endblock %}

{% block content %}

    <div class = "resultados">
        <p class = "titulo-res">Resultados da Pesquisa</p>

        {% if query %}
        <p class="quant-res">
            {{ total_resultados }} resultado{% if total_resultados != 1 %}s{% endif %}
            encontrado{% if total_resultados != 1 %}s{% endif %} para "{{ query }}"
        </p>
    {% else %}
        <p class="quant-res">
            {{ total_resultados }} resultado{% if total_resultados != 1 %}s{% endif %}
            encontrado{% if total_resultados != 1 %}s{% endif %} com os filtros selecionados
        </p>
    {% endif %}
    </div>

    {% if predios_encontrados or locais %}
        {% for predio in predios_encontrados %}
        <div class="container-pesq">
            <div class="img-res">
                <i data-lucide="building" class="icone-predio2"></i>
                <p class="titulo-card">{{ predio.nome }}</p>
                <p class="subtit-card">Prédio</p>
            </div>
            <div class="res-txt">
                <div class="div-pesq">
                    <p class="nome-pesq">{{ predio.nome }}</p>

                    {% if user.is_authenticated %}
                        <form method="post" action="{% url 'mapa:favoritar_predio' predio.id %}">
                        {% csrf_token %}
                            <button type="submit" class="favorites-btn2" aria-label="Favoritar prédio">
                                {% if predio.id in favoritos_predios_ids %}
                                    <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                                {% else %}
                                    <i data-lucide="heart" class="icone-coracao-vazio"></i>
                                {% endif %}
                            </button>
                        </form>
                    {% else %}
                            <a href="{% url 'mapa:favoritar_login_required' %}" class="favorites-btn2">
                                <i data-lucide="heart" class="icone-coracao-vazio"></i>
                            </a>
                    {% endif %}
                </div>
                
                <div class="div-pesq2">
                    <i data-lucide="map-pin" class="icone-textos"></i>
                    <p class="text-pesq">Edifício completo</p>
                </div>
                    <div class="div-pesq3">
                        <div class="div-pesq">
                            <p class="tit-inf-adc">Informações Adicionais</p>
                        </div>
                        {% if predio.descricao %}
                        <div class="div-pesq2">  
                            <i data-lucide="info" class="icone-textos"></i>  
                            <p class="text-pesq">{{ predio.descricao }}</p>
                        </div>
                        {% else %}
                        <div class="div-pesq2">  
                            <i data-lucide="info" class="icone-textos"></i>  
                            <p class="text-pesq">Sem descrição</p>      
                        </div>
                        {% endif %}
                    </div>    
                {% load l10n %}
                <div class="div-pesq5">
                    <a href="{% url 'mapa:mapa' %}?lat={{ predio.coordenadas.0|unlocalize }}&lng={{ predio.coordenadas.1|unlocalize }}" class="marcar-btn">
                        <span data-lucide="map-pinned" class="icones-btns"></span>Marcar como destino
                    </a>
                    <a href="{% url 'available_locations' %}" class="extras-btn">
                        <span data-lucide="route" class="icones-btns"></span>Ver Locais
                    </a>
                    <button class="extras-btn"><span data-lucide="share-2" class="icones-btns"></span>Compartilhar</button>
                </div>
            </div>
        </div>
        {% endfor %}
        
        {% for local in locais %}
            <div class="container-pesq">
                <div class="img-res">
                    <i data-lucide="building" class="icone-predio2"></i>
                    <p class="titulo-card">{{ local.predio.nome }}</p>
                    <p class="subtit-card"> 
                            {% if local.andar.isdigit %}
                                {{ local.andar }}º andar
                            {% else %}
                                {{ local.andar }}
                            {% endif %}
                    </p>
                </div>
                <div class="res-txt">
                    <div class="div-pesq">
                        <p class="nome-pesq">{{ local.nome }}</p>
                        
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'mapa:favoritar_local' local.id %}">
                            {% csrf_token %}
                                <button type="submit" class="favorites-btn2" aria-label="Favoritar local">
                                    {% if local.id in favoritos_locais_ids %}
                                        <i data-lucide="heart" class="icone-coracao-preenchido"></i>
                                    {% else %}
                                        <i data-lucide="heart" class="icone-coracao-vazio"></i>
                                    {% endif %}
                                </button>
                            </form>
                        {% else %}
                            <a href="{% url 'mapa:favoritar_login_required' %}" class="favorites-btn2">
                                <i data-lucide="heart" class="icone-coracao-vazio"></i>
                            </a>
                        {% endif %}
                    
                    
                    </div>


                    <div class="div-pesq2">
                        <i data-lucide="building" class="icone-textos"></i>
                        <p class="text-pesq">{{ local.predio.nome }}</p>
                    </div>
                    <div class="div-pesq2">
                        <i data-lucide="layers" class="icone-textos"></i>
                        <p class="text-pesq">{% if local.andar.isdigit %}
                                                {{ local.andar }}º andar
                                            {% else %}
                                                {{ local.andar }}
                                            {% endif %} </p>
                    </div>
                    <div class="div-pesq2">
                        <i data-lucide="door-open" class="icone-textos"></i>
                        <p class="text-pesq">{{ local.get_tipo_display }}</p>
                    </div>
                    <div class="div-pesq3">
                        <div class="div-pesq">
                            <p class="tit-inf-adc">Informações Adicionais</p>
                        </div>
                        <div class="div-pesq4">
                            {% if local.informacoes_extras.capacidade %}
                            <p class="text-pesq">
                                Capacidade: <span class="text-pesq2">{{ local.informacoes_extras.capacidade }} pessoas</span>
                            </p>
                            {% endif %}
                            {% if local.informacoes_extras.tipo %}
                            <p class="text-pesq">
                                Tipo:  <span class="text-pesq2">{{ local.get_tipo_display }}</span>
                            </p>
                            {% endif %}
                            {% if local.informacoes_extras.recursos %}
                            <p class="text-pesq">
                                Recursos: <span class="text-pesq2">{{ local.informacoes_extras.recursos }}</span>
                            </p>
                            {% endif %}
                            {% if local.informacoes_extras.acessibilidade %}
                            <p class="text-pesq">
                                Acesso:  <span class="text-pesq2">{{ local.informacoes_extras.acessibilidade }}</span>
                            </p>
                            {% endif %}
                        </div>
                    </div>    
                    {% load l10n %}
                    <div class="div-pesq5">
                        <a href="{% url 'mapa:mapa' %}?lat={{ local.predio.coordenadas.0|unlocalize }}&lng={{ local.predio.coordenadas.1|unlocalize }}" class="marcar-btn">
                            <span data-lucide="map-pinned" class="icones-btns"></span>Marcar como destino
                        </a>
                        <a href="{% url 'info_ambientes' local.id %}" class="extras-btn">
                            <span data-lucide="info" class="icones-btns"></span>Mais informações
                        </a>
                    </div>
                </div>
    </div>
    {% endfor %}
    
        <div class = "resultados">
            <p class = "quant-res">Fim dos resultados da pesquisa</p>
        </div>

    {% else %}
        <div class="resultados">
            {% if query %}
        <p class="quant-res">
            {{ total_resultados }} resultado{% if total_resultados != 1 %}s{% endif %}
            encontrado{% if total_resultados != 1 %}s{% endif %} para "{{ query }}"
        </p>
    {% else %}
        <p class="quant-res">
            {{ total_resultados }} resultado{% if total_resultados != 1 %}s{% endif %}
            encontrado{% if total_resultados != 1 %}s{% endif %} com os filtros selecionados
        </p>
    {% endif %}
        </div>

    {% endif %}



{% endblock %}